### ISSUE TITLE
安装后运行部署时显示错误

### ISSUE THREAD

**Issue by DSLZL** [wuzheng228/hexo-pro#12]
```
ERROR Plugin load failed: hexo-pro
Error: Cannot find module 'body-parser'
Require stack:
- C:\Users\Administrator\Desktop\hexo\md\node_modules\hexo-pro\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at req (C:\Users\Administrator\Desktop\hexo\md\node_modules\hexo\dist\hexo\index.js:240:31)
    at C:\Users\Administrator\Desktop\hexo\md\node_modules\hexo-pro\index.js:3:18
    at C:\Users\Administrator\Desktop\hexo\md\node_modules\hexo\dist\hexo\index.js:248:20
    at tryCatcher (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\Administrator\Desktop\hexo\md\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
```
访问http://localhost:4000/pro/
只有Cannot GET /pro/

**Comment by DSLZL** [comment]
已解决，使用npm 安装body-parser即可，我觉得应该把安装hexo时，若有npm没有安装的模块，可以放上来让其他人知道

**Comment by wuzheng228** [comment]
> 已解决，使用npm 安装body-parser即可，我觉得应该把安装hexo时，若有npm没有安装的模块，可以放上来让其他人知道

我看了下hexo-pro的package-json 没有body-parser，可能跟hexo的版本有关系，在某个版本hexo移除了这个模块，或者是我开发的时候其他hexo插件引入了这个模块所以没有报错

**Comment by owen8877** [comment]
我把 hexo 升级到 7.0 之后也遇到这个问题。建议把 body-parser 加到 dependency 里面。

**Comment by wuzheng228** [comment]
> 我把 hexo 升级到 7.0 之后也遇到这个问题。建议把 body-parser 和 extend 加到 dependency 里面。

加好了，偷懒了
