### ISSUE TITLE
求回复 ： hexo server -d 报错

### ISSUE THREAD

**Issue by NorthPoet** [wuzheng228/hexo-pro#18]
> 请问这个错误要怎么解决啊 ， 试了好多方法但是并不起任何效果

PS F:\blog> npm install --save hexo-pro  
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

added 25 packages in 2s
PS F:\blog> hexo server -d
INFO  Validating config
ERROR Plugin load failed: hexo-pro
Error: Cannot find module 'extend'
Require stack:
- F:\blog\node_modules\hexo-pro\update.js
- F:\blog\node_modules\hexo-pro\post_api.js
- F:\blog\node_modules\hexo-pro\api.js
- F:\blog\node_modules\hexo-pro\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (F:\blog\node_modules\hexo-pro\update.js:5:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (F:\blog\node_modules\hexo-pro\post_api.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (F:\blog\node_modules\hexo-pro\api.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)

**Comment by wuzheng228** [comment]
我得晚上看看，原理上不该报这个错，extend模块应该是hexo自带的

**Comment by NorthPoet** [comment]
好的 ， 麻烦了🌹

**Comment by wuzheng228** [comment]
> 好的 ， 麻烦了🌹

应该已经好了npm install hexo-pro@1.0.11, 原因是我没有添加extend依赖，之前也有人遇到过，已经修复了

**Comment by NorthPoet** [comment]
> > 好的，麻烦了🌹
> 
> 应该已经好了` npm install hexo-pro@1.0.11`，重新安装一下，原因是我没有添加extend依赖，之前也有人遇到过，已经修复了，你也可以`npm install extend body-parser`把出口的依赖重新安装一下就可以使用了

已解决 ， 谢谢

**Comment by NorthPoet** [comment]
请问这个要怎么解决啊

![image](https://github.com/wuzheng228/hexo-pro/assets/93069489/329b12f9-5b19-4adf-862e-845f51653cfe)

**Comment by wuzheng228** [comment]
> 请问这个要怎么解决啊
> 
> ![image](https://private-user-images.githubusercontent.com/93069489/294065628-329b12f9-5b19-4adf-862e-845f51653cfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzI4OTQsIm5iZiI6MTcwNDMzMjU5NCwicGF0aCI6Ii85MzA2OTQ4OS8yOTQwNjU2MjgtMzI5YjEyZjktNWIxOS00YWRmLTg2MmUtODQ1ZjUxNjUzY2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAxNDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMmViYWQ5NGQ2ZmVhMzJmNDI1MDFhYTk3NDhlYTAyZTI0YTUzMWYwNWE4NTkyYjhmN2VmNzMwY2ZjOTMxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-mgm-I17GC8Zg3GTMoeGALJ2-FNNpu2ErETUmC5MwPs)
影响运行么

**Comment by wuzheng228** [comment]
找到原因了我修一下，发一下

**Comment by NorthPoet** [comment]
不影响🤣 ， 还有个问题就是这个hexo-pro只能在本地访问嘛 ， 部署之后好像并没有显示/pro这个界面 ， 还有就是在本地发布的文章 ， 好像并没有提交上去 ， 不知道是不是我的原因 , 请问有什么解决办法嘛

![image](https://github.com/wuzheng228/hexo-pro/assets/93069489/b63ae332-a623-4d41-9f5f-3446ff30f577)

![image](https://github.com/wuzheng228/hexo-pro/assets/93069489/7c46822f-bac5-4718-85bd-a41513e0fc1c)

**Comment by wuzheng228** [comment]
我修复了，重新装一下1.0.12版本就行了，gitpage部署hexo，只是代理hexo生成的静态文件，用不了这个插件的。hexo-pro这个插件需要使用到hexo的http服务模式，我自己是在自己的的服务器上部署的，提供http服务就能在线编辑博客了，你也可以本地编辑发到将静态文件gitpage上去

**Comment by NorthPoet** [comment]
谢谢解答
