### ISSUE TITLE
打印出错

### ISSUE THREAD

**Issue by Boring1998** [wuzheng228/hexo-pro#26]
YAMLException: bad indentation of a mapping entry (104:16)

 101 | hexo_pro:
 102 |   username: Boring
 103 |   password: w125201314
 104 |   avatar: https: image for your own avata
----------------------^
 105 |   secret: xxx // jwt secret key
 106 |
    at generateError (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:183:10)
    at throwError (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:187:9)
    at readBlockMapping (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:1182:7)
    at composeNode (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:1441:12)
    at readBlockMapping (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:1164:11)
    at composeNode (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:1441:12)
    at readDocument (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:1625:3)
    at loadDocuments (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:1688:5)
    at Object.load (D:\BaiduSyncdisk\Hexo\node_modules\js-yaml\lib\loader.js:1714:19)
    at Hexo.yamlHelper (D:\BaiduSyncdisk\Hexo\node_modules\hexo\dist\plugins\renderer\yaml.js:22:30)
    at Hexo.tryCatcher (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\method.js:15:34)
    at D:\BaiduSyncdisk\Hexo\node_modules\hexo\dist\hexo\render.js:73:28
    at tryCatcher (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (D:\BaiduSyncdisk\Hexo\node_modules\bluebird\js\release\async.js:15:14)

**Comment by Boring1998** [comment]
[_config.txt](https://github.com/user-attachments/files/16086600/_config.txt)

**Comment by Boring1998** [comment]
> 看报错是104行缩进不正确，你把你的配置文件发我我看看,试试下面这个配置
> 
> ```yaml
> hexo_pro:
>   username: admin
>   password: 123456
>   avatar: https://example.com/your-own-avatar.jpg
>   secret: 123
> ```

用了你的文件就可以了，好神奇
