### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ZGGzgg** [wuzheng228/hexo-pro#28]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:659:11)
    at /data/data/com.termux/files/home/my-blog/node_modules/hexo-pro/index.js:104:17
    at call (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:235:7)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:183:5)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at call (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:248:3)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:183:5)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:161:14)
    at jsonParser (/data/data/com.termux/files/home/my-blog/node_modules/body-parser/lib/types/json.js:113:7)
    at call (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:239:7)
    at next (/data/data/com.termux/files/home/my-blog/node_modules/connect/index.js:183:5)

**Comment by wuzheng228** [comment]
应该不影响使用把
